services:
  server:
    build:
      context: .
    ports:
      - 5000:5000
    volumes: 
      - .:/app
    restart: on-failure
    develop:  
      watch:
        - path: .
          action: rebuild